---
- name: Init
  hosts: windows
  gather_facts: false
  any_errors_fatal: true
  roles:
    - init
  tags:
    - init

- name: Common Role
  hosts: windows,linux
  gather_facts: true
  roles:
    - common
  tags:
    - common

- name: Vyos Role
  hosts: vyos
  gather_facts: false
  roles:
    - vyos
  tags:
    - vyos

- name: dcpromo
  hosts: pdc
  gather_facts: false
  roles:
    - dcpromo
  tags:
    - dcpromo

- name: Create Users
  hosts: pdc
  gather_facts: false
  roles:
    - create_users
    - group_assignment
  tags:
    - create_users

- name: File Share
  hosts: file
  gather_facts: false
  roles:
    - fileserver
  tags:
    - fileserver

- name: Mapped Drive
  hosts: pdc
  gather_facts: false
  roles:
    - role: mapped_drive
      when: map_drive_letter is defined
  tags:
    - mapped_drive

- name: squid
  hosts: proxy
  gather_facts: false
  become: true
  roles:
    - squid
  tags:
    - squid

- name: wordpress-pv
  hosts: wordpress-pv
  gather_facts: false
  become: true
  roles:
    - docker
    - wordpress-pv
  tags:
    - wordpress-pv

- name: dns
  hosts: pdc
  gather_facts: false
  roles:
    - dns
  tags:
    - dns

- name: ae_gpo
  hosts: pdc
  gather_facts: false
  roles:
    - role: ae_gpo
    - role: disable_defender
      when: "groups.get('ae', []) | length > 0"
  tags:
    - ae_gpo
    - disable_defender

- name: Strip APIPA
  hosts: members
  gather_facts: false
  roles:
    - strip_apipa
  tags:
    - strip_apipa

- name: Join Domain
  hosts: members
  gather_facts: false
  roles:
    - domain_member_retry
  tags:
    - domain_member_retry

- name: Additional DC
  hosts: additional_dc
  gather_facts: false
  roles:
    - additional_dc
  tags:
    - additional_dc

- name: dc_status
  hosts: pdc,additional_dc
  gather_facts: false
  roles:
    - dc_status
  tags:
    - dc_status