ansible_host: "10.255.240.199"

# SimSpace provisions: eth0 = first data-plane (shared with mgmt 10.255.240.199/20)
network_interfaces:
  - name: "eth0"                      # PP-Services gateway (mgmt shares)
    ipv4:
      address: "172.16.2.1"
      netmask: "255.255.255.0"
      type: "ethernet"
      ospf: true
  - name: "eth1"                      # PP-Business-Processing-Department gateway
    ipv4:
      address: "172.16.3.1"
      netmask: "255.255.255.0"
      type: "ethernet"
      ospf: true
  - name: "eth2"                      # PP-Eng-Department gateway
    ipv4:
      address: "172.16.4.1"
      netmask: "255.255.255.0"
      type: "ethernet"
      ospf: true
  - name: "eth3"                      # PP-LS-Department gateway
    ipv4:
      address: "172.16.5.1"
      netmask: "255.255.255.0"
      type: "ethernet"
      ospf: true
  - name: "eth4"                      # PP-IS-Department gateway
    ipv4:
      address: "172.16.6.1"
      netmask: "255.255.255.0"
      type: "ethernet"
      ospf: true
  - name: "eth5"                      # switch-10 transit to pp-internal-router
    ipv4:
      address: "172.16.0.42"
      netmask: "255.255.255.252"
      type: "ethernet"
      ospf: true

bgp:
  - as: 65001
    neighbor:
      ip: "172.16.0.41"               # pp-internal-router
      as: 65001
