ansible_host: 10.255.240.145
network_interfaces:
  - name: "Ethernet0"
    ipv4:
      address: "10.255.240.145"
      netmask: "255.255.240.0"
      gateway: ""
  - name: "Ethernet1"
    ipv4:
      address: "172.16.80.10"
      netmask: "255.255.255.248"
      gateway: "172.16.80.9"
    dns:
      - "172.16.2.7"
