ansible_host: "10.255.240.195"

network_interfaces:
  - name: "eth0"                      # management
    ipv4:
      address: "10.255.240.195"
      netmask: "255.255.240.0"
      type: "ethernet"
  - name: "eth1"                      # switch-2 transit to pp-internal-firewall
    ipv4:
      address: "172.16.0.17"
      netmask: "255.255.255.252"
      type: "ethernet"
      ospf: true
  - name: "eth2"                      # switch-1 transit to pp-external-firewall
    ipv4:
      address: "172.16.0.10"
      netmask: "255.255.255.252"
      type: "ethernet"
      ospf: true

bgp:
  - as: 65001
    neighbor:
      ip: "172.16.0.18"               # pp-internal-firewall
      as: 65001
  - as: 65001
    neighbor:
      ip: "172.16.0.9"                # pp-external-firewall
      as: 65001
