---
- name: apply netplan
  ansible.builtin.command:
    cmd: netplan apply

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart unbound supervisor
  ansible.builtin.systemd:
    name: airfield-unbound-supervise.service
    state: restarted

- name: restart unbound supervisor timer
  ansible.builtin.systemd:
    name: airfield-unbound-supervise.timer
    state: restarted
